### ISSUE TITLE
Questions about development

### ISSUE THREAD

**Issue by PerMalmberg** [Adarnof/adarnauth#1]
Hello,

A short question regarding development of AA and this new fork.

What's the time frame of this fork? Do you plan to replace the current version with this one?

The reason I'm asking is that we have some features we'd like to develop, but we'd rather not redo it all in a month or so.

Thanks,

**Comment by Adarnof** [comment]
I'd like to get the core done by next month in a usable state.

This would be an excellent opportunity for my professional training in project management to come out. Sadly I don't have any training in anything. So you'll have to settle for my mspaint diagram of what I'm doing.

Figure 1. The current state of AllianceAuth
![AllianceAuth v1](http://i.imgur.com/VWecWxv.png)

Figure 2. The chunk v2 is replacing.
![AllianecAuth v2](http://i.imgur.com/ULypHA3.png)

If what's in development is within that brown spraypaint, it won't make it to v2. The stuff outside it will be grafted onto v2. Note that service managers will survive to some extent but require a major rewrite to handle how I'll be implementing services in v2.

Core models like User and EVE things will of course be replicated in v2 with a few differences.

I should post this to a wiki or something.

**Comment by PerMalmberg** [comment]
A month you say? Better stop working so hard on v1 then :)

What we have in mind does partly fall inside the brown line. We'll have to think of something smart.

Also, how much of the current models will stay the same, or at least similar? Specifically the models relating APIs?

**Comment by Adarnof** [comment]
If people would just stop breaking v1...

API keys are nearly identical. I've added a NullBooleanField to record if the key is valid. Haven't come up with a way to link characters to an API key - leaning towards putting a ManyToMany to EVECharacter inside the EVEApiKeyPair.

To what extent? If it depends on the models, you'll be fine, just having to change the field names referenced.

**Comment by PerMalmberg** [comment]
Ok, thanks for the info. I'm sure I'll be back with more later.

**Comment by nizzan** [comment]
Has there been any progress?
Any ETA on when we can start looking at moving from V1 to V2?

**Comment by Adarnof** [comment]
Progress? Sure, it's in a usable form.

But I'm not satisfied and am in the process of rewriting as the readme describes. No eta.
